AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  SourceBucketName:
    Type: String
    Description: Name of the S3 bucket where PDF files are uploaded

Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: 'Lambda function to convert PDF files to text'
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::844028273225:role/lambda_s3'
      Environment:
        Variables:
          TARGET_BUCKET: gl-inter-store
      Layers:
        - 'arn:aws:lambda:ap-northeast-1:844028273225:layer:tika:1'
      Events:
        S3PdfUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucketName
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Suffix: .pdf