AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::197444073346:role/search-engine-cloudformation-role'
      Environment:
        Variables:
          TARGET_BUCKET: gl-inter-store-esanchez
      Layers:
        - 'arn:aws:lambda:us-east-2:197444073346:layer:tika:1'
      Events:
        S3PdfUpload:
          Type: S3
          Properties:
            Bucket: pdf-source-docs-esanchez # Replace with your actual source bucket name
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Suffix: .pdf
