AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  SourceBucketName:
    Type: String
    Description: Name of the S3 bucket where PDF files are uploaded

Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'

  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: 'PDF to Text conversion Lambda function'
      MemorySize: 512
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TARGET_BUCKET: gl-inter-store
      Events:
        S3PdfUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucketName
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Suffix: .pdf
      Layers:
        - "arn:aws:lambda:us-east-2:197444073346:layer:tika:1"